codecov:
  # Should Codecov wait for all other statuses to pass before sending its status.
  require_ci_to_pass: yes
  bot: "codecov-io"

coverage:
  precision: 2
  round: down
  range: "29...100"
  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        # basic settings
        target: auto
        threshold: 5%
        base: auto
        # advanced settings
        branches:
        - master
        if_ci_failed: error #success, failure, error, ignore
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
