services:
  # api:
  #   environment:
  #     # Adds opentelemetry endpoint.
  #     FASTAPI_PYTORCH_POSTGRESQL_SANDBOX_OPENTELEMETRY_ENDPOINT: "http://otel-collector:4317"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.53.0
    volumes:
      # Adds config for opentelemetry.
    - ./deploy/otel-collector-config.yml:/config.yml
    command: --config config.yml
    ports:
      # Collector's endpoint
    - "4317:4317"

  # The latest Jaeger v1.35 release introduced the ability to receive OpenTelemetry trace data via the OpenTelemetry Protocol (OTLP), which all OpenTelemetry SDKs are required to support. This is a follow-up to the previous announcement to retire Jaeger's "classic" client libraries.

  # With this new capability, it is no longer necessary to use the Jaeger exporters with the OpenTelemetry SDKs, or to run the OpenTelemetry Collector in front of the Jaeger backend. Using the OTLP exporter, the SDKs can be configured to send the data directly to the Jaeger backend. The OTLP receiver accepts data via gRPC and HTTP endpoints (gRPC mode had an issue that was patched in 1.35.1).
  # NOTE: SOURCE: https://medium.com/jaegertracing/introducing-native-support-for-opentelemetry-in-jaeger-eb661be8183c
  jaeger:
    image: jaegertracing/all-in-one:1.35
    hostname: jaeger
    # The OTLP receiver must be enabled via COLLECTOR_OTLP_ENABLED=true
    environment:
    - COLLECTOR_OTLP_ENABLED=true
    - JAEGER_AGENT_HOST=0.0.0.0
      # - COLLECTOR_ZIPKIN_HOST_PORT=":9411"
    # SOURCE: https://www.jaegertracing.io/docs/next-release/getting-started/
    # Port	Protocol	Component	Function
    # 6831	UDP	agent	accept jaeger.thrift over Thrift-compact protocol (used by most SDKs)
    # 6832	UDP	agent	accept jaeger.thrift over Thrift-binary protocol (used by Node.js SDK)
    # 5775	UDP	agent	(deprecated) accept zipkin.thrift over compact Thrift protocol (used by legacy clients only)
    # 5778	HTTP	agent	serve configs (sampling, etc.)
    # 16686	HTTP	query	serve frontend
    # 4317	HTTP	collector	accept OpenTelemetry Protocol (OTLP) over gRPC, if enabled
    # 4318	HTTP	collector	accept OpenTelemetry Protocol (OTLP) over HTTP, if enabled
    # 14268	HTTP	collector	accept jaeger.thrift directly from clients
    # 14250	HTTP	collector	accept model.proto
    # 9411	HTTP	collector	Zipkin compatible endpoint (optional)
    ports:
      # Jaeger UI
    - 16686:16686
    # There are two more ports added to the export list, 4317 and 4318, used by the OTLP receiver to listen for gRPC and HTTP connections.
    # accept OpenTelemetry Protocol (OTLP) over gRPC, if enabled
    # - 4317:4317
    # accept OpenTelemetry Protocol (OTLP) over HTTP, if enabled
    - 4318:4318

    # accept jaeger.thrift over Thrift-compact protocol (used by most SDKs)
    # - "6831:6831/udp"
    # accept jaeger.thrift over Thrift-binary protocol (used by Node.js SDK)
    # - "6832:6832/udp"
    # (deprecated) accept zipkin.thrift over compact Thrift protocol (used by legacy clients only)
    # - 5775:5775

    # serve configs (sampling, etc.)
    # - 5778:5778

    # accept jaeger.thrift directly from clients
    # - 14268:14268
    # # accept model.proto
    - 14250:14250
    # Zipkin compatible endpoint (optional)
    # - 9411:9411
