name: fastapi_pytorch_postgresql_sandbox3
channels:
- pytorch
- conda-forge
- defaults
- fastchan
- apple
dependencies:
- python=3.10
- pip>=22.2
- pytorch
- torchmetrics
- torch-fidelity
- torchtext
- torchvision
- fastai=2.7.10
- albumentations=1.3.0
- timm
  # I suggest to keep the other deps sorted for convenience.
  # To determine what the latest versions should be, run:
  #
  # ```shell
  # sed -E 's/invokeai/invokeai-updated/;20,99s/- ([^=]+)==.+/- \1/' environment-mac.yml > environment-mac-updated.yml
  # CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac-updated.yml && conda list -n invokeai-updated | awk ' {print "  - " $1 "==" $2;} '
  # ```
- apple::tensorflow-deps
- coloredlogs=15.0
- eventlet
- humanfriendly=10.0
- imageio-ffmpeg=0.4
- imageio=2.21
- imgaug=0.4
- matplotlib=3.6.2
- numpy=1.23
- openh264=2.3
- py-opencv=4.6
- scikit-image
- scikit-learn
- scipy=1.9
- tensorboard=2.11.0
- transformers=4.23
- pip:
  - tqdm
  - better_exceptions
  - torchsummary
  - bpython
  - imutils
  - uritools
  - rich[jupyter]
  - icecream
  - black[jupyter]
  - pylint
  - isort
  - autopep8
  - autoflake
  - pdbpp
  - mlxtend
  - torchinfo
  - invoke
  - logging_tree
  - loguru
  - pydantic[email]
  - picklescan
  - git+https://github.com/openai/CLIP.git@main#egg=clip
  - git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k-diffusion
  - viztracer
  - pytype
  - pyannotate
  - mypy
  - py-spy
  - watermark
  - pyfiglet
  - pynguin
      # - memray
  - torch-tb-profiler
  - fastapi
  - uvicorn
  - pydantic
  - yarl
  - ujson
  - ormar
  - alembic
  - asyncpg
  - psycopg2-binary
  - redis
  - aiofiles
  - httptools
  - aio-pika
  - prometheus-client
  - prometheus-fastapi-instrumentator==5.9.1
  - opentelemetry-api
  - opentelemetry-sdk
  - opentelemetry-exporter-otlp
  - opentelemetry-instrumentation
  - opentelemetry-instrumentation-fastapi
  - opentelemetry-instrumentation-redis
  - opentelemetry-instrumentation-asyncpg
  - opentelemetry-instrumentation-aio-pika
  - loguru
  - aiokafka
  - tensorflow-macos
  - tensorflow-metal
  - pytest
  - pre-commit
  - wemake-python-styleguide
  - pytest-cov
  - anyio
  - pytest-env
  - fakeredis
  - httpx
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1
